object Versions {
    const val KOTLIN_VERSION = "1.3.72"
    const val COROUTINES = "1.3.3"
    const val ROOM = "2.2.3"
    const val MATERIAL = "1.1.0"
    const val LIFECYCLE = "2.2.0"
    const val CORE_KTX = "1.3.1"
    const val FRAGMENT_KTX = "1.2.5"
    const val CONSTRAIN_LAYOUT = "1.1.3"
    const val APPCOMPAT = "1.1.0"
    const val TIMBER = "4.7.1"
    const val LEAKCANARY = "2.0"
    const val TEST = "1.2.0"
    const val EXT = "1.1.1"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.12"
    const val ROBOELECTRIC = "4.3.1"
    const val MOCKITO = "2.2.0"
    const val MOCKK = "1.9.3"
    const val ASSERTJ = "3.16.1"
    const val ESPRESSO = "3.2.0"
    const val FRAGMENT_TEST = "1.2.5"
    const val MOCK_WEB_SERVER = "4.2.2"
    const val PLAY_CORE = "1.6.4"
}
